[package]
name = "checkers_lib"
version = "0.2.0"
authors = ["Godlesschild"]
edition = "2021"

[dependencies]
itertools = "0.10.5"
thiserror = "1.0.40"

[dev-dependencies]
pretty_assertions = "1.3.0"
